version: '3.8'
services:
  web:
    image: flask_pvica_informe
    container_name: flask_pvica_informe
    restart: always
    env_file: .env
    build:
        context: .
        dockerfile: Dockerfile
    networks:
      - postgres-network
      - apps
    volumes:
      - ./uploads:/uploads
networks:
  postgres-network:
    external: true
  apps:
    external: true
